---
- name: config_chrony | Configuring Chrony
  ansible.builtin.template:
    src: etc/chrony/chrony.conf.j2
    dest: "{{ chrony_config }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart {{ chrony_service }}
