---
- name: set_facts | Define Debian Facts
  ansible.builtin.set_fact:
    chrony_config: /etc/chrony/chrony.conf
    chrony_service: chrony
  when: ansible_facts.os_family == "Debian"

- name: set_facts | Define RedHat Facts
  ansible.builtin.set_fact:
    chrony_config: /etc/chrony.conf
    chrony_service: chronyd
  when: ansible_facts.os_family == "RedHat"
