---
# handlers file for ansible-chrony
- name: restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
  become: true

- name: restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
  become: true
